# Generated by Django 3.2.12 on 2022-03-29 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('sold_price', models.IntegerField()),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Comparable',
                'verbose_name_plural': 'Comparables',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_count', models.IntegerField(default=1)),
                ('bed_diff', models.IntegerField(default=1)),
                ('bath_diff', models.IntegerField(default=1)),
                ('year_built_diff', models.IntegerField(default=10)),
                ('distance_diff', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('sqft_diff', models.IntegerField(default=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),
    ]
