# Generated by Django 3.2.12 on 2022-04-20 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('bed_diff', models.IntegerField(default=1)),
                ('bath_diff', models.DecimalField(decimal_places=1, default=0.5, max_digits=3)),
                ('year_built_diff', models.IntegerField(default=10)),
                ('sqft_diff', models.IntegerField(default=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='LeadProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('list_price', models.IntegerField(blank=True, null=True)),
                ('list_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('link', models.URLField(blank=True, null=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='search.search')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='Comparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('sold_price', models.IntegerField()),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('link', models.URLField(blank=True, null=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='search.search')),
            ],
            options={
                'verbose_name': 'Comparable',
                'verbose_name_plural': 'Comparables',
            },
        ),
    ]
