# Generated by Django 3.2.12 on 2022-04-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparable',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadproperty',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='year_built_diff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SoldProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField()),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('sold_price', models.IntegerField()),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_props', to='search.search')),
            ],
            options={
                'verbose_name': 'Sold Property',
                'verbose_name_plural': 'Sold Properties',
            },
        ),
        migrations.CreateModel(
            name='ForSaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField()),
                ('list_price', models.IntegerField(blank=True, null=True)),
                ('list_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('link', models.URLField(blank=True, null=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_sale_props', to='search.search')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
