# Generated by Django 3.2.12 on 2022-04-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='distance_diff',
        ),
    ]
